### PR TITLE
Put "create new tag" on bottom of results

### PR DESCRIPTION
**Pull request by riking**
image

### CODE REVIEW

**Comment by eviltrout** [comment]
Shouldn't it be on top though? That way you can hit enter to create your new tag as you'd expect?

**Comment by riking** [comment]
Nope, as I've seen from experience on Meta, you want to heavily favor reusing existing tags over creating new ones. `docke<ENTER>` should pick the `docker` tag for sure.

**Comment by coding-horror** [comment]
This is true, you want to heavily favor reuse of existing tags...

**Comment by eviltrout** [comment]
:+1:

**Pull request merged**
