### PR TITLE
Create client.pt_PT.yml

### PR DESCRIPTION
**Pull request by jfoclpf**

### CODE REVIEW

**Comment by eviltrout** [comment]
Thanks

**Comment by jfoclpf** [comment]
thank you

João Pimentel Ferreira http://joãopimentel.eu

2015-07-03 22:57 GMT+02:00 Robin Ward notifications@github.com:

**Comment by jfoclpf** [comment]
I udpated my tagging plugin in our discourse and the translations aren't
still available
http://forum.mubi.pt/tags

can you kindly check?

thank you so much

João Pimentel Ferreira http://joãopimentel.eu

2015-07-03 22:57 GMT+02:00 João Pimentel Ferreira <
joao.pimentel.ferreira@gmail.com>:

**Comment by jfoclpf** [comment]
can you kindly accept the next one in the same file?
https://github.com/discourse/discourse-tagging/pull/39
there was a tiny error

João Pimentel Ferreira http://joãopimentel.eu

2015-07-03 22:57 GMT+02:00 Robin Ward notifications@github.com:

**Pull request merged**
